config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#  resources :archives
#  resources :couples
#  resources :special_classes
#  resources :courses
#  resources :students
#  resources :lessons
#  resources :weddings

scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  resources :archives, path: 'interesados' do
    get 'search', on: :collection
  end
end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :couples, path: 'parejas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :special_classes, path: 'clasesparticulares' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :courses, path: 'cursos' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :students, path: 'alumnas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :lessons, path: 'clases' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :weddings, path: 'matrimonios' do
      get 'search', on: :collection
      get 'todos', on: :collection
    end
  end

  devise_for :users, controllers: { registrations: "registrations"}

  resources :users, only: [:index, :show]
  get 'hola/index'
  get 'hola/portada'
  get 'agenda' => 'lessons#agenda'
  get 'bloquearhorario' => 'lessons#bloquear'

  authenticated :user do
    root to: 'hola#portada', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  # root 'hola#portada'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/couple.rb
class Couple < ApplicationRecord
# Relaciones con usuarios y con clases
  has_many :lessons, as: :bloggable, dependent: :destroy
  belongs_to :user
end

app/controllers/couples_controller.rb
class CouplesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_couple, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /couples
  # GET /couples.json
  def index
    @couples = Couple.all
  end

  # GET /couples/1
  # GET /couples/1.json
  def show
  # Cookies para construir la relación bloggable. Reemplazar id_blog y tipo_blog según corresponda.
    cookies[:id_blog] = @couple.id
    cookies[:tipo_blog] = "Couple"
  end

  # GET /couples/new
  def new
    @couple = Couple.new
  end

  # GET /couples/1/edit
  def edit
  end

  # POST /couples
  # POST /couples.json
  def create
    @couple = Couple.new(couple_params)

    respond_to do |format|
      if @couple.save
        format.html { redirect_to @couple, notice: 'Se creó el baile en pareja.' }
        format.json { render :show, status: :created, location: @couple }
      else
        format.html { render :new }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couples/1
  # PATCH/PUT /couples/1.json
  def update
    respond_to do |format|
      if @couple.update(couple_params)
        format.html { redirect_to @couple, notice: 'Se actualizó el baile en pareja.' }
        format.json { render :show, status: :ok, location: @couple }
      else
        format.html { render :edit }
        format.json { render json: @couple.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couples/1
  # DELETE /couples/1.json
  def destroy
    @couple.destroy
    respond_to do |format|
      format.html { redirect_to couples_url, notice: 'Se borró el baile en pareja.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_couple
      @couple = Couple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def couple_params
      params.require(:couple).permit(:nombre1, :nombre2, :contacto, :email, :telefono, :comoseenteraron, :descuento, :comentarios, :comentarios_pago)
    end
end

app/helpers/couples_helper.rb
module CouplesHelper
end

app/views/couples/_form.html.erb
<%= form_for(couple) do |f| %>
  <% if couple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(couple.errors.count, "error") %> prohibited this couple from being saved:</h2>

      <ul>
      <% couple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%# f.label :nombre1 %>
    <%= f.text_field :nombre1, class: 'form-control', placeholder: 'Nombre de la 1° persona' %>
  </div>

  <div class="field form-group">
    <%# f.label :nombre2 %>
    <%= f.text_field :nombre2, class: 'form-control', placeholder: 'Nombre de la 2° persona' %>
  </div>

  <div class="field form-group">
    <%# f.label :contacto %>
    <%= f.text_field :contacto, class: 'form-control', placeholder: 'Nombre del contacto, si es un tercero' %>
  </div>

  <div class="field form-group">
    <%# f.label :email %>
    <%= f.text_field :email, class: 'form-control', placeholder: 'E-mail de contacto', type: "email" %>
  </div>

  <div class="field form-group">
    <%# f.label :telefono %>
    <%= f.text_field :telefono, class: 'form-control', placeholder: 'Teléfono de contacto', type: 'tel' %>
  </div>

  <div class="field form-group">
    <%# f.label :comoseenteraron %>
    <%= f.text_field :comoseenteraron, class: 'form-control', placeholder: '¿Cómo se enteraron de la academia?' %>
  </div>

  <div class="field form-group">
    <%# f.label :descuento %>
    <%= f.text_field :descuento, class: 'form-control', placeholder: '¿Tienen un descuento? Indicar aquí.' %>
  </div>

  <div class="field form-group">
    <%# f.label :comentarios %>
    <%= f.text_field :comentarios, class: 'form-control', placeholder: '¿Comentarios sobre la pareja? Indicar aquí.' %>
  </div>

  <div class="field form-group">
    <%= f.text_area :comentarios_pago, class: "form-control", placeholder: "En caso de haber comentarios respecto al pago, indicar aquí:" %>
  </div>

  <div class="actions">
    <%= f.submit 'Inscribir baile en pareja', :class => 'btn btn-block btn-primary' %>
  </div>
<% end %>

app/views/couples/edit.html.erb
<h3 class="my-3">Editar baile en pareja</h3>
<hr>

<%= render 'form', couple: @couple %>

<p><small>Otras acciones (no guardan los cambios realizados):</small></p>
<div class="btn-group mb-3" role="group" aria-label="Otras acciones:">
  <%= link_to 'Mostrar ficha', @couple, class: "btn btn-secondary", role: "button" %>
  <%= link_to 'Volver a lista', couples_path, class: "btn btn-secondary", role: "button" %>
</div>

app/views/couples/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row my-3">
  <div class="col-8">
    <h3>Bailes en Pareja</h3>
  </div>
  <div class="col-4">
    <%= link_to '➕ Nuevo', new_couple_path, class: "btn btn-block btn-primary", role: "button"  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre 1° persona</th>
      <th>Nombre 2° persona</th>
      <th>Contacto (si es un tercero)</th>
      <th>E-mail</th>
      <th>Telefono</th>
      <th>¿Cómo se enteró de la academia?</th>
      <th>Descuento</th>
      <th>Comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @couples.each do |couple| %>
      <tr>
        <td><%= couple.nombre1 %></td>
        <td><%= couple.nombre2 %></td>
        <td><%= couple.contacto %></td>
        <td><%= couple.email %></td>
        <td><%= couple.telefono %></td>
        <td><%= couple.comoseenteraron %></td>
        <td><%= couple.descuento %></td>
        <td><%= couple.comentarios %></td>
        <td><%= link_to 'Ver', couple, class: "btn btn-block btn-info" %></td>
        <td><%= link_to 'Editar', edit_couple_path(couple), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', couple, class: "btn btn-block btn-danger", method: :delete, data: { confirm: '¿Segura?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Inscribir nueva pareja', new_couple_path, class: "btn btn-block btn-secondary my-3", role: "button" %>

app/views/couples/new.html.erb
<h3 class="my-3">Nuevo baile en pareja</h3>
<hr>

<%= render 'form', couple: @couple %>

<%= link_to 'Volver', couples_path, class: 'btn btn-block btn-secondary' %>

app/views/couples/show.html.erb
<div class="row my-3">
  <div class="col-lg-4">
    <h3>Baile en pareja:</h3>
    <p class="lead"><%= @couple.nombre1 %> y <%= @couple.nombre2 %></p>
  </div>
  <div class="col-lg-8">
    <div class="row">
      <div class="col-lg-4">
        <p><%= link_to '✏ Editar', edit_couple_path(@couple), class: "btn btn-block btn-warning", role: "button" %></p>
      </div>
      <div class="col-lg-4">
        <p><%= link_to '⬅ Volver', couples_path, class: "btn btn-block btn-secondary", role: "button" %></p>
      </div>
      <div class="col-lg-4">
        <p><%= link_to '📦 Archivar', new_archive_path, class: "btn btn-block btn-warning", role: "button" %></p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <%= link_to 'Agregar nueva clase', new_lesson_path, class: "btn btn-block btn-primary", role: "button" %>
      </div>
    </div>
  </div>
</div>
<hr>

<p id="notice"><%= notice %></p>

<ul class="list-group">
  <li class="list-group-item">1° persona: <strong><%= @couple.nombre1 %></strong></li>
  <li class="list-group-item">2° persona: <strong><%= @couple.nombre2 %></strong></li>
  <li class="list-group-item">Contacto (de ser un tercero): <%= @couple.contacto %></li>
  <li class="list-group-item">E-mail de contacto: <%= @couple.email %></li>
  <li class="list-group-item">Teléfono de contacto: <%= @couple.telefono %></li>
</ul>

<button class="btn btn-outline-warning btn-md btn-block my-3" type="button" data-toggle="collapse" data-target="#colapsarInfo" aria-expanded="false" aria-controls="colapsarInfo">
  Mostrar más información
</button>
<div class="collapse" id="colapsarInfo">
  <ul class="list-group">
    <li class="list-group-item">¿Cómo se enteraron de la Academia?: <%= @couple.comoseenteraron %></li>
    <li class="list-group-item">Descuento: <%= @couple.descuento %></li>
    <li class="list-group-item">Comentarios: <%= @couple.comentarios %></li>
    <li class="list-group-item">Comentarios respecto al pago: <%= @couple.comentarios_pago %></li>
  </ul>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <h4>Información sobre clases</h4>
          <div class="table-responsive">
            <table class="table">
              <tr>
                <th>Clase</th>
                <th>Hora</th>
                <th colspan="2"></th>
              </tr>
              <% @couple.lessons.each do |lesson| %>
              <tr>
                <td><%= lesson.titulo %></td>
                <td><%= lesson.start_time %></td>
                <td><%= link_to "Ver", lesson, class: "btn btn-block btn-info", role: "button" %></td>
                <td><%= link_to "Editar", edit_lesson_path(lesson), class: "btn btn-block btn-primary", role: "button" %></td>
              </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>