config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#  resources :archives
#  resources :couples
#  resources :special_classes
#  resources :courses
#  resources :students
#  resources :lessons
#  resources :weddings

scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  resources :archives, path: 'interesados' do
    get 'search', on: :collection
  end
end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :couples, path: 'parejas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :special_classes, path: 'clasesparticulares' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :courses, path: 'cursos' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :students, path: 'alumnas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :lessons, path: 'clases' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :weddings, path: 'matrimonios' do
      get 'search', on: :collection
      get 'todos', on: :collection
    end
  end

  devise_for :users, controllers: { registrations: "registrations"}

  resources :users, only: [:index, :show]
  get 'hola/index'
  get 'hola/portada'
  get 'agenda' => 'lessons#agenda'
  get 'bloquearhorario' => 'lessons#bloquear'

  authenticated :user do
    root to: 'hola#portada', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  # root 'hola#portada'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :bloggable, polymorphic: true
# Registra uploaders
  mount_uploader :video, VideoDeClaseUploader
  mount_uploaders :videos, VideoDeClaseUploader
# def set_success(format, opts)
#   self.success = true
# end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  skip_authorize_resource :agenda, :only => :read

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # Agenda
  def agenda
    @meetings = Lesson.all
  end

  # Formulario nuevo para bloquear horario
  def bloquear
    @lesson = Lesson.new(titulo: "Horario bloqueado")
    @meetings = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new(bloggable_id: cookies[:id_blog], bloggable_type: cookies[:tipo_blog])
    @meetings = Lesson.all
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Se creó la clase satisfactoriamente.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Se actualizó la clase satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Se borró la clase satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:fecha, :titulo, :notas, :start_time, :end_time, :video, :pago, :valor_clase, :profesora, :bloggable_type, :bloggable_id, {videos: []})
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_agenda.html.erb
<div class="card">
  <div class="card-body">
    <h1 class="display-3 text-center">Hoy</h1>
    <%= calendar number_of_days: 1, events: @meetings do |date, meetings| %>
      <% meetings.each do |meeting| %>
        <div class="card">
          <div class="card-body">
            <h3><%= meeting.start_time.strftime("%H:%M") %></h3>
            <% if meeting.bloggable_type == "Wedding" %>
              <p class="p-1 p-matri">👰🏻 Matrimonio</p>
              <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %> y <%= link_to meeting.bloggable.try(:nombre2), edit_lesson_path(meeting) %></a></p>
            <% elsif meeting.bloggable_type == "Couple" %>
              <p class="p-1 p-parejas">👯 Baile en Pareja</p>
              <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %> y <%= link_to meeting.bloggable.nombre2, edit_lesson_path(meeting) %></a></p>
            <% elsif meeting.bloggable_type == "SpecialClass" %>
              <p class="p-1 p-parejas">👯 Baile en Pareja</p>
              <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %></a></p>
            <% else %>
              <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %></a></p>
            <% end %>
          </div>
        </div>
      <% end %>

    <% end %>
    <p><%= link_to "Clases de la semana", agenda_path, class: "btn btn-block btn-primary", role: "button" %></p>
  </div>
</div>

app/views/lessons/_disponibilidad.html.erb
<div class="card">
  <div class="card-body">
    <%= week_calendar number_of_weeks: 2, events: @meetings do |date, meetings| %>
      <% meetings.each do |meeting| %>
        <div class="card">
          <div class="card-body">
            <h3><%= meeting.start_time.strftime("%H:%M") %></h3>
            <% if meeting.bloggable_type == "Wedding" %>
              <p class="p-1 p-matri">👰🏻 Matrimonio</p>
              <p class="lead"><%= link_to meeting.bloggable.nombre1, edit_lesson_path(meeting) %> y <%= link_to meeting.bloggable.nombre2, edit_lesson_path(meeting) %></a></p>
            <% elsif meeting.bloggable_type == "Couple" %>
              <p class="p-1 p-parejas">👯 Baile en Pareja</p>
              <p class="lead"><%= link_to meeting.bloggable.nombre1, edit_lesson_path(meeting) %> y <%= link_to meeting.bloggable.nombre2, edit_lesson_path(meeting) %></a></p>
            <% elsif meeting.bloggable_type == "SpecialClass" %>
              <p class="p-1 p-parejas">👯 Baile en Pareja</p>
              <p class="lead"><%= link_to meeting.bloggable.nombre1, edit_lesson_path(meeting) %></a></p>
            <% else %>
              <p class="lead"><%= link_to meeting.bloggable.nombre1, edit_lesson_path(meeting) %></a></p>
            <% end %>
          </div>
        </div>
      <% end %>

    <% end %>
  </div>
</div>

app/views/lessons/_form.html.erb
<%= form_for(lesson) do |f| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="card card-body">
      <%= f.text_field :bloggable_type, class: "d-none" %>
      <%= f.text_field :bloggable_id, class: "d-none" %>
      <div class="d-none">
        <%= f.date_select :fecha %>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="field form-group">
            <p>Hora de inicio</p>
            <%= f.datetime_select :start_time, {start_hour: 8, end_hour: 23, minute_step: 15}, class: "custom-select" %>
          </div>
        </div>
        <div class="col-12">
          <div class="field form-group">
            <p>Hora de término</p>
            <%= f.datetime_select :end_time, {start_hour: 8, end_hour: 23, minute_step: 15}, class: "custom-select" %>
          </div>
        </div>
      </div>
    </div>

  <button class="btn btn-outline-success btn-md btn-block my-2" type="button" data-toggle="collapse" data-target="#colapsarNotas" aria-expanded="false" aria-controls="colapsarNotas">
      Ingresa las notas de la clase
  </button>
  <div class="collapse" id="colapsarNotas">
    <div class="card card-body">
      <div class="field form-group">
        <%= f.label :titulo %>
        <%= f.text_field :titulo, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :profesora %>
        <%= f.text_field :profesora, class: "form-control" %>
      </div>
      <div class="field form-group">
        <%= f.label :notas %>
        <%= f.text_area :notas, class: "form-control" %>
      </div>
      <div class="field form-group">
        <p class="lead">Videos de Clase</p>
        <%= f.file_field :videos, multiple: true %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= f.submit 'Registrar clase', :class => 'btn btn-block btn-primary my-2' %>
  </div>
<% end %>

app/views/lessons/agenda.html.erb
<p id="notice"><%= notice %></p>

<h3 class="my-3">Agenda Semanal</h3>
<hr>

<div class="card">
  <div class="card-body">
    <%= week_calendar events: @meetings do |date, meetings| %>
      <p class="lead text-center"><%= l date %></p>
      <% meetings.each do |meeting| %>
      <div class="card">
        <div class="card-body">
          <h3><%= meeting.start_time.strftime("%H:%M") %> - <%= meeting.end_time.strftime("%H:%M") %></h3>
          <% if meeting.bloggable_type == "Wedding" %>
            <p class="p-1 p-matri">👰🏻 Matrimonio</p>
            <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %> y <%= link_to meeting.bloggable.try(:nombre2), edit_lesson_path(meeting) %></a></p>
            <% elsif meeting.bloggable_type == "Couple" %>
              <p class="p-1 p-parejas">👯 Baile en Pareja</p>
              <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %> y <%= link_to meeting.bloggable.nombre2, edit_lesson_path(meeting) %></a></p>
          <% elsif meeting.bloggable_type == "SpecialClass" %>
            <p class="p-1 p-particular">💃🏻 Clase particular</p>
            <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %></a></p>
          <% else %>
            <p class="lead"><%= link_to meeting.bloggable.try(:nombre1), edit_lesson_path(meeting) %></a></p>
          <% end %>
        </div>
      </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/lessons/bloquear.html.erb
<h3 class="my-3">Bloquear horario</h1>
<hr>

<div class="row">
  <div class="col-xl-6">
    <h4 class="text-center">Horas disponibles</h4>
    <%= render 'disponibilidad' %>
  </div>
  <div class="col-xl-6">
    <h4 class="text-center">Agenda el horario bloqueado</h4>
    <%= render 'form', lesson: @lesson %>
  </div>
</div>

<%= link_to 'Volver', lessons_path, class: 'btn btn-block btn-secondary my-3', role: "button" %>

app/views/lessons/edit.html.erb
<h3 class="my-3">Edición de clase</h1>
<hr>

<%= render 'form', lesson: @lesson %>

<div class="btn-group mb-3" role="group" aria-label="Otras acciones:">
  <%= link_to 'Mostrar clase', @lesson, class: "btn btn-secondary", role: "button" %>
  <% if @lesson.bloggable_type == "Wedding" %>
    <%= link_to 'Mostrar matrimonio', wedding_path(@lesson.bloggable.id), class: "btn btn-secondary", role: "button" %>
  <% elsif @lesson.bloggable_type == "Couple" %>
    <%= link_to 'Mostrar baile en pareja', couple_path(@lesson.bloggable.id), class: "btn btn-secondary", role: "button" %>
  <% elsif @lesson.bloggable_type == "SpecialClass" %>
    <%= link_to 'Mostrar clase particular', special_class_path(@lesson.bloggable.id), class: "btn btn-secondary", role: "button" %>
  <% end %>
  <%= link_to 'Volver', lessons_path, class: "btn btn-secondary", role: "button" %>
</div>

app/views/lessons/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row my-3">
  <div class="col-md-8">
    <h3>Clases</h3>
  </div>
  <div class="col-md-4">
    <%= link_to '➕ Nueva', new_lesson_path, class: "btn btn-block btn-primary", role: "button"  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Fecha</th>
      <th>Titulo</th>
      <th>Notas</th>
      <th>¿Para qué persona?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lessons.each do |lesson| %>
      <tr>
        <td><%= lesson.fecha %></td>
        <td><%= lesson.titulo %></td>
        <td><%= lesson.notas %></td>
        <td><% if lesson.bloggable_type == "Wedding" %>Matrimonio de <% end %><%# lesson.bloggable.nombre1 %></td>
        <td><%= link_to 'Ver', lesson, class: "btn btn-block btn-info" %></td>
        <td><%= link_to 'Editar', edit_lesson_path(lesson), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', lesson, class: "btn btn-block btn-danger", method: :delete, data: { confirm: '¿Segura?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'Inscribir nueva clase', new_lesson_path, class: "btn btn-block btn-secondary my-3", role: "button" %>

app/views/lessons/new.html.erb
<h3 class="my-3">Nueva clase</h1>
<hr>
<div class="row">
  <div class="col-12">
    <div class="alert alert-warning alert-dismissible fade in" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <% if cookies[:tipo_blog] == "Wedding" %>
        Crearás una clase para el <strong>matrimonio</strong> de <strong><%= @lesson.bloggable.nombre1 %></strong> y <strong><%= @lesson.bloggable.nombre2 %></strong>. Si no está correcto, <%= link_to "vuelve a la lista de matrimonios", weddings_path %>.
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-xl-6">
    <h4 class="text-center">Horas disponibles</h4>
    <%= render 'disponibilidad' %>
  </div>
  <div class="col-xl-6">
    <h4 class="text-center">Agenda la clase</h4>
    <%= render 'form', lesson: @lesson %>
  </div>
</div>

<%# link_to 'Volver', lessons_path, class: 'btn btn-block btn-secondary my-3', role: "button" %>

app/views/lessons/show.html.erb
<div class="row">
  <div class="col-md-8 col-lg-9 col-xl-10">
    <h3>Clase</h3>
    <% if @lesson.bloggable_type == "Wedding" %>
      <p class="p-1 p-matri">👰🏻 Matrimonio</p>
      <p class="lead"><%= link_to @lesson.bloggable.try(:nombre1), edit_lesson_path(@lesson) %> y <%= link_to @lesson.bloggable.try(:nombre2), edit_lesson_path(@lesson) %></a></p>
      <% elsif @lesson.bloggable_type == "Couple" %>
        <p class="p-1 p-parejas">👯 Baile en Pareja</p>
        <p class="lead"><%= link_to @lesson.bloggable.try(:nombre1), edit_lesson_path(@lesson) %> y <%= link_to @lesson.bloggable.nombre2, edit_lesson_path(@lesson) %></a></p>
    <% elsif @lesson.bloggable_type == "SpecialClass" %>
      <p class="p-1 p-particular">💃🏻 Clase particular</p>
      <p class="lead"><%= link_to @lesson.bloggable.try(:nombre1), edit_lesson_path(@lesson) %></a></p>
    <% else %>
      <p class="lead">Horario bloqueado</a></p>
    <% end %>
    <p class="small text-center bg-faded hidden-sm-down">Registrada el día <%= l @lesson.fecha %></p>
    <p class="card-text small text-center hidden-md-up">Clase realizada por <%= @lesson.profesora %></p>
  </div>
  <div class="col-md-4 col-lg-3 col-xl-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-subtitle text-center hidden-md-up">Acciones:</h5>
        <div class="d-flex justify-content-center">
          <div class="btn-group-vertical" role="group" aria-label="Acciones para esta clase">
            <% if @lesson.bloggable_type == "Wedding" %>
              <%= link_to '⬅ Volver', wedding_path(@lesson.bloggable.id), class: "btn btn-secondary", role: "button" %>
            <% elsif @lesson.bloggable_type == "Couple" %>
              <%= link_to '⬅ Volver', couple_path(@lesson.bloggable.id), class: "btn btn-secondary", role: "button" %>
            <% elsif @lesson.bloggable_type == "SpecialClass" %>
              <%= link_to '⬅ Volver', special_class_path(@lesson.bloggable.id), class: "btn btn-secondary", role: "button" %>
            <% else %>
              <%= link_to '⬅ Volver', lessons_path, class: "btn btn-secondary", role: "button" %>
            <% end %>
            <%= link_to '✏ Editar', edit_lesson_path(@lesson), class: "btn btn-warning", role: "button" %>
            <%= link_to '🗑 Borrar', @lesson, class: "btn btn-danger", method: :delete, data: { confirm: '¿Segura?' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>

<p id="notice"><%= notice %></p>

<div class="row mb-3">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <p>Inicio:</p>
        <p class="lead"><%= @lesson.start_time.strftime("%d/%m/%Y %H:%M") %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card">
      <div class="card-body">
        <p>Término:</p>
        <p class="lead"><%= @lesson.end_time.strftime("%d/%m/%Y %H:%M") %></p>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <div class="card-group">
      <div class="card mb-3">
        <div class="card-body">
          <h4 class="card-title"><%= @lesson.titulo %></h4>
          <%= @lesson.notas %>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-body">
          <p class="lead card-title">Videos de la clase</p>
          <% @lesson.videos.each do |video| %>
          <div class="embed-responsive embed-responsive-16by9 mb-2">
            <%= video_tag(video, controls: true, class: "embed-responsive-item") %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>