config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#  resources :archives
#  resources :couples
#  resources :special_classes
#  resources :courses
#  resources :students
#  resources :lessons
#  resources :weddings

scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  resources :archives, path: 'interesados' do
    get 'search', on: :collection
  end
end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :couples, path: 'parejas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :special_classes, path: 'clasesparticulares' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :courses, path: 'cursos' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :students, path: 'alumnas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :lessons, path: 'clases' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :weddings, path: 'matrimonios' do
      get 'search', on: :collection
      get 'todos', on: :collection
    end
  end

  devise_for :users, controllers: { registrations: "registrations"}

  resources :users, only: [:index, :show]
  get 'hola/index'
  get 'hola/portada'
  get 'agenda' => 'lessons#agenda'
  get 'bloquearhorario' => 'lessons#bloquear'

  authenticated :user do
    root to: 'hola#portada', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  # root 'hola#portada'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wedding.rb
class Wedding < ApplicationRecord
# will_paginate
  self.per_page = 30
# Relaciones con usuarios y con clases
  has_many :lessons, as: :bloggable, dependent: :destroy
  belongs_to :user
# Configura uploaders
  mount_uploader :floordesign, DisenoDePisoUploader
  mount_uploader :song, SongUploader
  mount_uploader :avatar, PhotoUploader
# Incluye buscador
  include PgSearch
  pg_search_scope :buscar, against: [:nombre1, :nombre2]
  # Separador de código
    def code
      self.url_vals.split('/').last if self.url_vals
    end
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_wedding, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /weddings
  # GET /weddings.json
  def index
  # Muestra en la página los matrimonios con fecha de realización mayor o igual que hace 3 días.
    @weddings = Wedding.where("fecha_matri >= ?", 3.days.ago)
  # En el CSV, tira todos los matrimonios
    @wedding_archives = Wedding.all
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"matrimonios-plataforma-CP.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def todos
    @weddings = Wedding.all
  end

  def search
    @weddings = Wedding.buscar(params[:buscar]).page(params[:page])
  end

  # GET /weddings/1
  # GET /weddings/1.json
  def show
  # Cookies para construir la relación bloggable y el llenado de archivos.
    cookies[:id_blog] = @wedding.id
    cookies[:tipo_blog] = "Wedding"
    cookies[:mailusuaria] = @wedding.email_novia
    @cancion = @wedding.song?
    @youtube = @wedding.url_vals?
  end

  # GET /weddings/new
  def new
    @wedding = Wedding.new(user_id: cookies[:uidfu], nombre1: cookies[:arch_nombre], email_novia: cookies[:arch_email], telefono_novia: cookies[:arch_tel])
  end

  # GET /weddings/1/edit
  def edit
  end

  # POST /weddings
  # POST /weddings.json
  def create
    @wedding = Wedding.new(wedding_params)

    respond_to do |format|
      if @wedding.save
        cookies.delete(:uidfu)
        cookies.delete(:arch_nombre)
        cookies.delete(:arch_email)
        cookies.delete(:arch_tel)
        format.html { redirect_to @wedding, notice: 'Se creó el matrimonio satisfactoriamente.' }
        format.json { render :show, status: :created, location: @wedding }
      else
        format.html { render :new }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /weddings/1
  # PATCH/PUT /weddings/1.json
  def update
    respond_to do |format|
      if @wedding.update(wedding_params)
        format.html { redirect_to @wedding, notice: 'Se actualizó el matrimonio satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @wedding }
      else
        format.html { render :edit }
        format.json { render json: @wedding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weddings/1
  # DELETE /weddings/1.json
  def destroy
    @wedding.destroy
    respond_to do |format|
      format.html { redirect_to weddings_url, notice: 'Se borró el matrimonio satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wedding
      @wedding = Wedding.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wedding_params
      params.require(:wedding).permit(:nombre1, :nombre2, :fecha_matri, :origen, :url_vals, :comentarios, :telefono_novia, :telefono_novio, :email_novia, :email_novio, :tipo_descuento, :floordesign, :rut_novia, :rut_novio, :instagram_novia, :maspersonas, :contacto, :comentarios_pago, :song, :avatar, :user_id)
    end
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/weddings/_form.html.erb
<%= form_for(wedding) do |f| %>
  <% if wedding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wedding.errors.count, "error") %> prohibited this wedding from being saved:</h2>

      <ul>
      <% wedding.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.text_field :user_id, class: "d-none" %>
    <div class="row">
      <div class="col-sm-6">
        <p>Datos de la novia</p>
        <div class="field form-group">
          <%= f.text_field :nombre1, class: 'form-control', placeholder: 'Nombre de la novia' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :telefono_novia, class: 'form-control', placeholder: 'Teléfono de la novia' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :email_novia, class: 'form-control', placeholder: 'E-mail de la novia' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :rut_novia, class: 'form-control', placeholder: 'RUT de la novia' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :instagram_novia, class: 'form-control', placeholder: 'Cuenta en Instagram de la novia (URL)', type: "url" %>
        </div>
      </div>
      <div class="col-sm-6">
        <p>Datos del novio</p>
        <div class="field form-group">
          <%= f.text_field :nombre2, class: 'form-control', placeholder: 'Nombre del novio' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :telefono_novio, class: 'form-control', placeholder: 'Teléfono del novio' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :email_novio, class: 'form-control', placeholder: 'E-mail del novio' %>
        </div>
        <div class="field form-group">
          <%= f.text_field :rut_novio, class: 'form-control', placeholder: 'RUT del novio' %>
        </div>
      </div>
    </div>
    <button class="btn btn-primary my-3" type="button" data-toggle="collapse" data-target="#collapseNovias" aria-expanded="false" aria-controls="collapseNovias">
      ¿Necesitas agregar a más personas?
    </button>
    <div class="collapse" id="collapseNovias">
      <div class="card card-body">
        <div class="field form-group">
          <%= f.text_area :maspersonas, class: 'form-control', placeholder: 'Agrega a las personas que sean necesarias.' %>
        </div>
      </div>
    </div>

    <p class="lead">¿La persona que hizo el contacto no es la novia ni el novio?</p>
    <div class="field form-group">
      <%= f.text_area :contacto, class: 'form-control', placeholder: 'Ingresa todos los datos del contacto (nombre, teléfono y correo electrónico)' %>
    </div>

    <div class="field form-group">
      <p>Fecha del Matrimonio:</p>
      <%= f.date_select :fecha_matri, class: 'custom-select' %>
    </div>

    <div class="field form-group origen">
      <%= f.text_field :origen, class: 'form-control', placeholder: '¿Cómo se enteraron de la academia?' %>
    </div>

    <div class="field form-group">
      <%= f.text_field :tipo_descuento, class: 'form-control', placeholder: '¿Tienen un descuento? Indicar aquí' %>
    </div>

    <p class="lead">Foto de novios</p>
    <div class="field form-group">
      <%= f.file_field :avatar %>
      <label>
        <%= f.check_box :remove_avatar %>
        Quitar foto de novios
      </label>
    </div>

    <p class="lead">Diseño de Piso</p>
    <div class="field form-group">
      <%= f.file_field :floordesign %>
      <label>
        <%= f.check_box :remove_floordesign %>
        Quitar diseño de piso
      </label>
    </div>

    <p class="lead">¿Qué canción van a usar?</p>
    <div class="card-group">
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">Link de YouTube:</p>
          <div class="field form-group">
            <%= f.text_field :url_vals, class: 'form-control', placeholder: 'URL de YouTube (formato: http://youtu.be/xxxxxxxxx):' %>
          </div>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-body">
          <p class="card-text">Subir canción:</p>
          <div class="field form-group">
            <%= f.file_field :song %>
            <label>
              <%= f.check_box :remove_song %>
              Quitar canción
            </label>
          </div>
        </div>
      </div>
    </div>

    <p class="lead">Comentarios (pueden agregarse más adelante)</p>
    <div class="field form-group">
      <%= f.text_area :comentarios, class: 'form-control', placeholder: 'Comentarios generales:' %>
    </div>
    <div class="field form-group">
      <%= f.text_area :comentarios_pago, class: 'form-control', placeholder: 'Comentarios respecto al pago:' %>
    </div>

    <div class="actions">
      <%= f.submit 'Inscribir matrimonio', :class => 'btn btn-block btn-primary' %>
    </div>

<% end %>

app/views/weddings/_list.html.erb
<div class="card">
  <div class="card-block">
    <div id="filterrific_results">
      <div>
        <%= page_entries_info weddings %>
      </div>
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Nombre de la novia</th>
            <th>E-mail de la novia</th>
            <th>Teléfono de la novia</th>
            <th></th>
          </tr>
          <% weddings.each do |wedding| %>
          <tr>
            <td><%= link_to(wedding.nombre1, wedding_path(wedding)) %></td>
            <td><%= wedding.email_novia %></td>
            <td><%= wedding.telefono_novia %></td>
            <td><%= link_to 'Ver', wedding, class: "btn btn-block btn-info" %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<%= will_paginate weddings %>

app/views/weddings/edit.html.erb
<h3 class="my-3">Editar Matrimonio</h3>
<hr>

<%= render 'form', wedding: @wedding %>

<p><small>Otras acciones (no guardan los cambios realizados):</small></p>
<div class="btn-group mb-3" role="group" aria-label="Otras acciones:">
  <%= link_to 'Mostrar matrimonio', @wedding, class: "btn btn-secondary", role: "button" %>
  <%= link_to 'Volver a lista', weddings_path, class: "btn btn-secondary", role: "button" %>
</div>

app/views/weddings/index.csv.erb
<%- headers = ['Fecha de registro', 'Nombre de la novia', 'E-Mail de la novia', 'Teléfono de la novia', 'RUT de la novia', 'Instagram de la novia', 'Nombre del novio', 'E-mail del novio', 'Teléfono del novio', 'RUT del novio', '¿Hubo más personas?', 'Fecha de matrimonio', 'Origen', 'Descuento', 'Comentarios', 'Comentarios de pago'] -%>
<%= CSV.generate_line headers %>
<%- @wedding_archives.each do |archive| -%>
<%= CSV.generate_line([archive.created_at, archive.nombre1, archive.email_novia, archive.telefono_novia, archive.rut_novia, archive.instagram_novia, archive.nombre2, archive.email_novio, archive.telefono_novio, archive.rut_novio, archive.maspersonas, archive.fecha_matri.strftime("%d/%m/%Y"), archive.origen, archive.tipo_descuento, archive.comentarios, archive.comentarios_pago]) -%>
<%- end -%>

app/views/weddings/index.html.erb
<p id="notice"><%= notice %></p>

<div class="alert alert-info alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  Se muestran los matrimonios realizados hasta <strong>hace 3 días</strong>. <%= link_to 'Ver todos', todos_weddings_path %>.
</div>
<div class="row my-3">
  <div class="col-lg-3 col-xl-4">
    <h3>Matrimonios</h3>
  </div>
  <div class="col-lg-5 col-xl-4">
    <%= form_tag search_weddings_path, method: :get do %>
      <div class="row">
        <div class="col-sm-8 col-md-10 col-lg-8 my-1">
          <div class="form-group">
            <%= text_field_tag :buscar, params[:buscar], class: "form-control", placeholder: "Busca matrimonios:" %>
          </div>
        </div>
        <div class="col-sm-4 col-md-2 col-lg-4 my-1">
          <%= submit_tag "Buscar", class: "btn btn-info btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-2 my-1">
    <%= link_to '🗃 Descargar', weddings_path(format: :csv), :class => 'btn btn-block btn-secondary', :role => 'button'  %>
  </div>
  <div class="col-lg-2 my-1">
    <%= link_to '➕ Nuevo', new_wedding_path, class: "btn btn-block btn-primary", role: "button"  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre de la novia</th>
      <th>Nombre del novio</th>
      <th>Fecha de matrimonio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weddings.each do |wedding| %>
      <tr>
        <td><%= link_to(wedding.nombre1, wedding_path(wedding)) %></td>
        <td><%= wedding.nombre2 %></td>
        <td><%= l wedding.fecha_matri %></td>
        <td><%= link_to 'Ver', wedding, class: "btn btn-block btn-info" %></td><%# i18n!! %>
        <td><%= link_to 'Editar', edit_wedding_path(wedding), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', wedding, class: "btn btn-block btn-danger", method: :delete, data: { confirm: '¿Segura?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/weddings/index.js.erb
<%# app/views/weddings/index.js.erb %>
<% js = escape_javascript(
  render(partial: 'weddings/list', locals: { weddings: @weddings })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/weddings/new.html.erb
<h3 class="my-3">Nuevo Matrimonio</h3>
<hr>
<div class="alert alert-info alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  🕑 Tienes 10 minutos para inscribir este matrimonio.
</div>
<%= render 'form', wedding: @wedding %>
<hr>
<%= link_to 'Volver', weddings_path, class: 'btn btn-block btn-secondary' %><%# i18n!!! %>

app/views/weddings/search.html.erb
<div class="row my-3">
  <div class="col-md-8">
    <h3>Matrimonios</h3>
  </div>
  <div class="col-md-4">
    <%= link_to '➕ Nuevo', new_wedding_path, class: "btn btn-block btn-primary", role: "button"  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre de la novia</th>
      <th>Nombre del novio</th>
      <th>Fecha de matrimonio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weddings.each do |wedding| %>
      <tr>
        <td><%= link_to(wedding.nombre1, wedding_path(wedding)) %></td>
        <td><%= wedding.nombre2 %></td>
        <td><%= l wedding.fecha_matri %></td>
        <td><%= link_to 'Ver', wedding, class: "btn btn-block btn-info" %></td><%# i18n!! %>
        <td><%= link_to 'Editar', edit_wedding_path(wedding), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', wedding, class: "btn btn-block btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @weddings %>
</div>

app/views/weddings/show.html.erb
<div class="row">
  <div class="col-md-8 col-lg-9 col-xl-10 mb-3 mb-md-0">
    <h3 class="p-2 p-matri">👰🏻 Matrimonio</h3>
    <p class="lead"><%= @wedding.nombre1 %> y <%= @wedding.nombre2 %></p>
    <%= link_to '➕ Agregar nueva clase', new_lesson_path, class: "btn btn-block btn-primary", role: "button" %>
  </div>
  <div class="col-md-4 col-lg-3 col-xl-2">
    <% if current_user.admin? %>
    <div class="card">
      <div class="card-body">
        <h5 class="card-subtitle text-center hidden-md-up">Acciones:</h5>
        <div class="d-flex justify-content-center">
          <div class="btn-group-vertical" role="group" aria-label="Acciones para esta clase">
            <%= link_to '⬅ Volver', weddings_path, class: "btn btn-secondary", role: "button" %>
            <%= link_to '✏ Editar', edit_wedding_path(@wedding), class: "btn btn-warning", role: "button" %>
            <%= link_to '🗑 Borrar', @wedding, class: "btn btn-danger", method: :delete, data: { confirm: '¿Segura?' } %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<hr>

<p id="notice"><%= notice %></p>

<div class="card card-inverse card-info mb-3">
  <div class="card-body p-1 pt-3">
    <h6 class="card-subtitle text-center">Fecha de Matrimonio:</h6>
    <h3 class="card-title text-center"><%= l @wedding.fecha_matri %></h3>
  </div>
</div>

<div class="card-group">
  <div class="card mb-3">
    <div class="card-body">
      <p>Novia:</p>
      <p class="lead"><%= @wedding.nombre1 %></p>
      <p class="lead"><%= mail_to @wedding.email_novia %></p>
      <p class="lead"><%= link_to @wedding.telefono_novia, "tel:#{@wedding.telefono_novia}" %></p>
      <p class="lead"><%= @wedding.rut_novia %></p>
      <p class="lead"><%= link_to "Instagram", @wedding.instagram_novia, class: "btn btn-sm btn-block btn-outline-success", role: "button" %>
    </div>
  </div>
  <div class="card mb-3">
    <%= image_tag @wedding.avatar, class: "card-img-top img-fluid" %>
  </div>
  <div class="card mb-3">
    <div class="card-body">
      <p>Novio:</p>
      <p class="lead"><%= @wedding.nombre2 %></p>
      <p class="lead"><%= mail_to @wedding.email_novio %></p>
      <p class="lead"><%= link_to @wedding.telefono_novio, "tel:#{@wedding.telefono_novio}" %></p>
      <p class="lead"><%= @wedding.rut_novio %></p>
    </div>
  </div>
</div>

<div class="card-group">
  <div class="card mb-3">
    <div class="card-body">
      <p class="lead">Diseño de Piso</p>
    </div>
    <%= image_tag @wedding.floordesign, class: "img-fluid d-block mx-auto" %>
  </div>
  <div class="card mb-3 card-song">
    <div class="card-body">
      <p class="lead">Canción</p>
    </div>

    <% if @youtube %>
    <div class="embed-responsive embed-responsive-16by9">
      <iframe class="embed-responsive-item" src="//www.youtube.com/embed/<%= @wedding.code %>" allowfullscreen></iframe>
    </div>
    <% end %>
    <%= audio_tag(@wedding.song, controls: true) if @cancion %>
  </div>
</div>

<button class="btn btn-outline-info btn-md btn-block my-3" type="button" data-toggle="collapse" data-target="#colapsarPago" aria-expanded="false" aria-controls="colapsarPago">
  Información sobre clases
</button>
<div class="collapse" id="colapsarPago">
  <div class="card mb-3">
    <div class="card-body">
      <h4 class="card-title">Información sobre clases</h4>
      <p class="card-text">Comentarios del pago: <%= @wedding.comentarios_pago %></li>
      <div class="table-responsive">
        <table class="table">
          <tr>
            <th>Clase</th>
            <th>Hora</th>
            <th>Profesora</th>
            <th colspan="3"></th>
          </tr>
          <% @wedding.lessons.each do |lesson| %>
          <tr>
            <td><%= lesson.titulo %></td>
            <td><%= lesson.start_time.strftime("%d/%m/%Y %H:%M") %></td>
            <td><%= lesson.profesora %></td>
            <td><%= link_to "Ver", lesson, class: "btn btn-block btn-info", role: "button" %></td>
            <% if current_user.admin? %>
            <td><%= link_to "Editar", edit_lesson_path(lesson), class: "btn btn-block btn-warning", role: "button" %></td>
            <td><%= link_to 'Borrar', lesson, class: "btn btn-block btn-danger", method: :delete, data: { confirm: '¿Segura?' } %></td>
            <% end %>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

<% if current_user.admin? %>
<button class="btn btn-outline-warning btn-md btn-block my-3" type="button" data-toggle="collapse" data-target="#colapsarInfo" aria-expanded="false" aria-controls="colapsarInfo">
  Más información
</button>
<div class="collapse" id="colapsarInfo">
  <div class="row">
    <div class="col-12 mb-3">
      <ul class="list-group">
        <li class="list-group-item">¿Cómo se enteraron de la Academia?: <%= @wedding.origen %></li>
        <li class="list-group-item">Descuento: <%= @wedding.tipo_descuento %></li>
        <li class="list-group-item">Comentarios: <%= @wedding.comentarios %></li>
      </ul>
    </div>
  </div>
</div>
<% end %>

app/views/weddings/todos.html.erb
<p id="notice"><%= notice %></p>

<div class="row my-3">
  <div class="col-lg-5 col-xl-6">
    <h3>Matrimonios</h3>
  </div>
  <div class="col-lg-5 col-xl-4">
    <%= form_tag search_weddings_path, method: :get do %>
      <div class="row">
        <div class="col-sm-8 col-md-10 col-lg-8">
          <div class="form-group">
            <%= text_field_tag :buscar, params[:buscar], class: "form-control", placeholder: "Busca matrimonios:" %>
          </div>
        </div>
        <div class="col-sm-4 col-md-2 col-lg-4">
          <%= submit_tag "Buscar", class: "btn btn-info btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-2">
    <%= link_to '🗃 Descargar', weddings_path(format: :csv), :class => 'btn btn-block btn-primary', :role => 'button'  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre de la novia</th>
      <th>Nombre del novio</th>
      <th>Fecha de matrimonio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @weddings.each do |wedding| %>
      <tr>
        <td><%= link_to(wedding.nombre1, wedding_path(wedding)) %></td>
        <td><%= wedding.nombre2 %></td>
        <td><%= l wedding.fecha_matri %></td>
        <td><%= link_to 'Ver', wedding, class: "btn btn-block btn-info" %></td><%# i18n!! %>
        <td><%= link_to 'Editar', edit_wedding_path(wedding), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', wedding, class: "btn btn-block btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>