config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#  resources :archives
#  resources :couples
#  resources :special_classes
#  resources :courses
#  resources :students
#  resources :lessons
#  resources :weddings

scope(path_names: { new: 'nuevo', edit: 'editar' }) do
  resources :archives, path: 'interesados' do
    get 'search', on: :collection
  end
end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :couples, path: 'parejas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :special_classes, path: 'clasesparticulares' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :courses, path: 'cursos' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :students, path: 'alumnas' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nueva', edit: 'editar' }) do
    resources :lessons, path: 'clases' do
      get 'search', on: :collection
    end
  end

  scope(path_names: { new: 'nuevo', edit: 'editar' }) do
    resources :weddings, path: 'matrimonios' do
      get 'search', on: :collection
      get 'todos', on: :collection
    end
  end

  devise_for :users, controllers: { registrations: "registrations"}

  resources :users, only: [:index, :show]
  get 'hola/index'
  get 'hola/portada'
  get 'agenda' => 'lessons#agenda'
  get 'bloquearhorario' => 'lessons#bloquear'

  authenticated :user do
    root to: 'hola#portada', as: :authenticated_root
  end
  root to: redirect('/users/sign_in')

  # root 'hola#portada'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/archive.rb
class Archive < ApplicationRecord
# Incluye buscador
  include PgSearch
  pg_search_scope :buscar, against: [:nombre]
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_archive, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.all
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"datos-plataforma-CP.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def search
    @archives = Archive.buscar(params[:buscar]).page(params[:page])
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
    cookies[:arch_nombre] = { value: @archive.nombre, expires: 10.minutes.from_now }
    cookies[:arch_email] = { value: @archive.email, expires: 10.minutes.from_now }
    cookies[:arch_tel] = { value: @archive.telefono, expires: 10.minutes.from_now }
  end

  # GET /archives/new
  def new
    @archive = Archive.new
  end

  # GET /archives/1/edit
  def edit
  end

  # POST /archives
  # POST /archives.json
  def create
    @archive = Archive.new(archive_params)

    respond_to do |format|
      if @archive.save
        cookies.delete(:arch_nombre)
        cookies.delete(:arch_email)
        cookies.delete(:arch_tel)
        format.html { redirect_to @archive, notice: 'Se creó el registro satisfactoriamente.' }
        format.json { render :show, status: :created, location: @archive }
      else
        format.html { render :new }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /archives/1
  # PATCH/PUT /archives/1.json
  def update
    respond_to do |format|
      if @archive.update(archive_params)
        format.html { redirect_to @archive, notice: 'Se actualizó el registro satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @archive }
      else
        format.html { render :edit }
        format.json { render json: @archive.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /archives/1
  # DELETE /archives/1.json
  def destroy
    @archive.destroy
    respond_to do |format|
      format.html { redirect_to archives_url, notice: 'Se borró el registro satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:nombre, :email, :telefono, :procedencia, :comentarios)
    end
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/views/archives/_form.html.erb
<%= form_for(archive) do |f| %>
  <% if archive.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(archive.errors.count, "error") %> prohibited this archive from being saved:</h2>

      <ul>
      <% archive.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% f.label :nombre %>
    <%= f.text_field :nombre, class: "form-control", placeholder: "¿A quién agregarás al archivo? Indica su nombre:" %>
  </div>

  <div class="field form-group">
    <% f.label :email %>
    <%= f.text_field :email, class: "form-control", placeholder: "E-mail de la persona:", type: "email" %>
  </div>

  <div class="field form-group">
    <% f.label :telefono %>
    <%= f.text_field :telefono, class: "form-control", placeholder: "Su teléfono:", type: "tel" %>
  </div>

  <div class="field form-group">
    <p>¿Cuál es el interés de la persona?</p>
    <%= f.radio_button :procedencia, "Matrimonio" %>
    <%= label :procedencia_matrimonio, "Matrimonio" %>
    <%= f.radio_button :procedencia, "Clase particular" %>
    <%= label :procedencia_particular, "Clase particular" %>
    <%= f.radio_button :procedencia, "Curso" %>
    <%= label :procedencia_curso, "Curso" %>
  </div>

  <div class="field form-group">
    <%= f.text_area :comentarios, class: "form-control", placeholder: "Comentarios:" %>
  </div>

  <div class="actions">
    <%= f.submit "Archivar", class: "btn btn-block btn-primary" %>
  </div>
<% end %>

app/views/archives/edit.html.erb
<h3 class="my-3">Editar archivo</h3>
<hr>

<%= render 'form', archive: @archive %>

<p><small>Otras acciones (no guardan los cambios realizados):</small></p>
<div class="btn-group mb-3" role="group" aria-label="Otras acciones:">
  <%= link_to 'Mostrar archivo', @archive, class: "btn btn-secondary", role: "button" %> |
  <%= link_to 'Volver a lista', archives_path, class: "btn btn-secondary", role: "button" %>
</div>

app/views/archives/index.csv.erb
<%- headers = ['Creado', 'Nombre', 'E-Mail', 'Teléfono', 'Procedencia', 'Comentarios'] -%>
<%= CSV.generate_line headers %>
<%- @archives.each do |archive| -%>
<%= CSV.generate_line([archive.created_at, archive.nombre, archive.email, archive.telefono, archive.procedencia, archive.comentarios]) -%>
<%- end -%>

app/views/archives/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row my-3">
  <div class="col-lg-5 col-xl-6">
    <h3>Personas interesadas</h3>
  </div>
  <div class="col-lg-5 col-xl-4">
    <%= form_tag search_archives_path, method: :get do %>
      <div class="row">
        <div class="col-sm-8 col-md-10 col-lg-8">
          <div class="form-group">
            <%= text_field_tag :buscar, params[:buscar], class: "form-control", placeholder: "Busca archivos:" %>
          </div>
        </div>
        <div class="col-sm-4 col-md-2 col-lg-4">
          <%= submit_tag "Buscar", class: "btn btn-info btn-block" %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-2">
    <%= link_to '🗃 Descargar', archives_path(format: :csv), :class => 'btn btn-block btn-primary', :role => 'button'  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>E-mail</th>
      <th>Teléfono</th>
      <th>Interés</th>
      <th>Comentarios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= archive.nombre %></td>
        <td><%= archive.email %></td>
        <td><%= archive.telefono %></td>
        <td><%= archive.procedencia %></td>
        <td><%= archive.comentarios %></td>
        <td><%= link_to 'Ver', archive, class: "btn btn-block btn-info" %></td>
        <td><%= link_to 'Editar', edit_archive_path(archive), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', archive, class: "btn btn-block btn-danger", method: :delete, data: { confirm: '¿Segura?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to 'New Archive', new_archive_path, class: "btn btn-block btn-secondary my-3", role: "button" %>

app/views/archives/new.html.erb
<h3 class="my-3">Nuevo archivo</h3>
<hr>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  Si vas a borrar un registro, debes hacerlo <strong>luego de archivar</strong>.
</div>

<%= render 'form', archive: @archive %>

<%= link_to 'Back', archives_path, class: 'btn btn-block btn-secondary my-3' %>

app/views/archives/search.html.erb
<div class="row my-3">
  <div class="col-md-8">
    <h3>Resultados de búsqueda: Archivos</h3>
  </div>
  <div class="col-md-4">
    <%= link_to '➕ Nuevo', new_archive_path, class: "btn btn-block btn-primary", role: "button"  %>
  </div>
</div>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>E-mail</th>
      <th>Teléfono</th>
      <th>Procedencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @archives.each do |archive| %>
      <tr>
        <td><%= link_to(archive.nombre, archive_path(archive)) %></td>
        <td><%= archive.email %></td>
        <td><%= archive.telefono %></td>
        <td><%= archive.procedencia %></td>
        <td><%= link_to 'Ver', archive, class: "btn btn-block btn-info" %></td><%# i18n!! %>
        <td><%= link_to 'Editar', edit_archive_path(archive), class: "btn btn-block btn-primary" %></td>
        <td><%= link_to 'Borrar', archive, class: "btn btn-block btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @archives %>
</div>

app/views/archives/show.html.erb
<div class="row">
  <div class="col-md-8 col-lg-9 col-xl-10 mb-3 mb-md-0">
    <h3 class="p-2 p-parejas text-white">🙋🏻 Persona interesada:</h3>
    <p class="lead"><%= @archive.nombre %></p>
      <% if @archive.procedencia == "Matrimonio" %>
        <%= link_to 'Inscribir en matrimonio', new_wedding_path, class: "btn btn-block btn-lg btn-primary", role: "button" %>
      <% elsif @archive.procedencia == "Clase particular" %>
        <%= link_to 'Inscribir en clase particular', new_special_class_path, class: "btn btn-block btn-lg btn-primary", role: "button" %>
      <% elsif @archive.procedencia == "Curso" %>
        <%= link_to 'Ver lista de cursos e inscribir', courses_path, class: "btn btn-block btn-lg btn-primary", role: "button" %>
      <% end %>
    <%# Agregar una acción diferenciada según el interés demostrado %>
  </div>
  <div class="col-md-4 col-lg-3 col-xl-2">
    <div class="card">
      <div class="card-body">
        <h5 class="card-subtitle text-center hidden-md-up">Acciones:</h5>
        <div class="d-flex justify-content-center">
          <div class="btn-group-vertical" role="group" aria-label="Acciones para esta clase">
            <%= link_to '⬅ Volver', archives_path, class: "btn btn-secondary", role: "button" %>
            <%= link_to '✏ Editar', edit_archive_path(@archive), class: "btn btn-warning", role: "button" %>
            <%= link_to '🗑 Borrar', @archive, class: "btn btn-danger", method: :delete, data: { confirm: '¿Segura?' } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<hr>

<p id="notice"><%= notice %></p>

<ul class="list-group">
  <li class="list-group-item">Nombre: <strong><%= @archive.nombre %></strong></li>
  <li class="list-group-item">E-mail: <%= @archive.email %></li>
  <li class="list-group-item">Teléfono: <%= @archive.telefono %></li>
  <li class="list-group-item">Procedencia: <%= @archive.procedencia %></li>
  <li class="list-group-item">Comentarios: <%= @archive.comentarios %></li>
</ul>